#!/usr/bin/env bash
sudo pacman -S --needed \
	plasma-desktop \
	kscreen \
	kscreenlocker \
	spectacle \
	bluedevil \
	breeze \
	breeze-gtk \
	breeze-plymouth \
	xdg-desktop-portal-kde \
	systemsettings \
	print-manager \
	powerdevil \
	polkit \
	polkit-kde-agent \
	plymouth-kcm \
	plasma5support \
	plasma-workspace-wallpapers \
	plasma-workspace \
	plasma-vault \
	plasma-systemmonitor \
	plasma-pa \
	plasma-nm \
	plasma-integration \
	plasma-firewall \
	plasma-disks \
	plasma-browser-integration \
	milou \
	libplasma \
	libksysguard \
	libkscreen \
	layer-shell-qt \
	kwrited \
	kwayland-integration \
	qt5-wayland \
	qt6-wayland \
	kde-gtk-config \
	kwallet \
	kwallet-pam \
	ksshaskpass \
	ksystemstats \
	kpipewire \
	plasma-pa \
	kmenuedit \
	kinfocenter \
	kglobalaccel \
	kglobalacceld \
	kgamma \
	kde-cli-tools \
	kactivitymanagerd \
	flatpak \
	flatpak-builder \
	discover \
	flatpak-kcm \
	drkonqi \
	sddm \
	sddm-kcm \
	dolphin \
	dolphin-plugins \
	kompare \
	baloo \
	baloo-widgets \
	kdegraphics-thumbnailers \
	kimageformats \
	libheif \
	qt6-imageformats \
	kdesdk-thumbnailers \
	ffmpegthumbs \
	taglib \
	audiocd-kio \
	udisks2 \
	kde-inotify-survey \
	kdenetwork-filesharing \
	kio-gdrive \
	kio-admin \
	kio-extras \
	kio-fuse \
	libappindicator-gtk3 \
	gwenview \
	qt5-imageformats \
	icoutils \
	iio-sensor-proxy \
	noto-fonts \
	noto-fonts-emoji \
	maliit-keyboard \
	power-profiles-daemon \
	switcheroo-control \
	xsettingsd \
	ark \
	unarchiver \
	unrar \
	
# Welcome App - plasma-welcome
# Thunderbolt Support - plasma-thunderbolt
# # Activites - plasma-activities & plasma-activites-stats
# kwin Compositor - kwin 
# Plasma addons (all kinds of addons for plasma?) - kdeplasma-addons
