#!/usr/bin/env bash

SYNC_DOTS(){

HOME="/home/jake"

# Source directories 
alacritty="$HOME/.config/alacritty"
btop="$HOME/.config/btop"
cava="$HOME/.config/cava"
easyeffects="$HOME/.config/easyeffects"
goverlay="$HOME/.config/goverlay"
htop="$HOME/.config/htop"
hyprland="$HOME/.config/hypr"
kitty="$HOME/.config/kitty"
lf="$HOME/.config/lf"
lutris="$HOME/.config/lutris"
Mangohud="$HOME/.config/MangoHud"
mpd="$HOME/.config/mpd"
mpv="$HOME/.config/mpv"
ncmpcpp="$HOME/.config/ncmpcpp"
openrazer="$HOME/.config/openrazer"
picom="$HOME/.config/picom"
pipewire="$HOME/.config/pipewire"
razergenie="$HOME/.config/razergenie"
sxhkd="$HOME/.config/sxhkd"
dotlocal="$HOME/.local/bin"
ssh="$HOME/.ssh"
gitconfig="$HOME/.gitconfig"
nvidiasettings="$HOME/.nvidia-settings-rc"
p10k="$HOME/.p10k.zsh"
xinitrc="$HOME/.xinitrc"
xresources="$HOME/.Xresources"
zprofile="$HOME/.zprofile"
zshrc="$HOME/.zshrc"

# Destination directory
dotconfig_dir="/mnt/truenas/jake/Linux/Backups/dotfiles/.config/"
homedots="/mnt/truenas/jake/Linux/Backups/dotfiles/"
localdots="/mnt/truenas/jake/Linux/Backups/dotfiles/.local/"

# Rsync command to sync the specified directories
rsync -avz  "$alacritty/" "$dotconfig_dir"
rsync -avz  "$btop/" "$dotconfig_dir"
rsync -avz  "$cava/" "$dotconfig_dir"
rsync -avz  "$easyeffects/" "$dotconfig_dir"
rsync -avz  "$goverlay/" "$dotconfig_dir"
rsync -avz  "$htop/" "$dotconfig_dir"
rsync -avz  "$hyprland/" "$dotconfig_dir"
rsync -avz  "$kitty/" "$dotconfig_dir"
rsync -avz  "$lf/" "$dotconfig_dir"
rsync -avz  "$lutris/" "$dotconfig_dir"
rsync -avz  "$Mangohud/" "$dotconfig_dir"
rsync -avz  "$mpd/" "$dotconfig_dir"
rsync -avz  "$mpv/" "$dotconfig_dir"
rsync -avz  "$ncmpcpp/" "$dotconfig_dir"
rsync -avz  "$openrazer/" "$dotconfig_dir"
rsync -avz  "$picom/" "$dotconfig_dir"
rsync -avz  "$pipewire/" "$dotconfig_dir"
rsync -avz  "$razergenie/" "$dotconfig_dir"
rsync -avz  "$sxhkd/" "$dotconfig_dir"
rsync -avz  "$dotlocal/" "$localdots"
rsync -avz  "$ssh/" "$dotconfig_dir"
rsync -avz  "$gitconfig" "$homedots"
rsync -avz  "$nvidiasettings" "$homedots"
rsync -avz  "$p10k" "$homedots"
rsync -avz  "$xinitrc" "$homedots"
rsync -avz  "$xresources" "$homedots"
rsync -avz  "$zprofile" "$homedots"
rsync -avz  "$zshrc" "$homedots"

}
SYNC_DOTS
